### ISSUE TITLE
Chatting App

### ISSUE THREAD

**Issue by GovindSingh9447** [Dezenix/mobile-screens#10]
### Description

Follow the contribution guidelines and code of conduct
**Design Chatting App:-**
   -Splash screen
   -Login Screen
   -Register Screen
   -Home Screen (_Where you can show posts, story, etc_.)
   -Friends List Screen
   -Message List Screen
   -Inbox Screen
  -Profile Screen

**Comment by RR-08** [comment]
Could you please add the Girl Script summer code label? I would like to work on this as part of it.
Please assign.

**Comment by RR-08** [comment]
Would like to work on this. Could you please assign it to me?

**Comment by GovindSingh9447** [comment]
Sure @RR-08.

**Comment by GovindSingh9447** [comment]
@RR-08  when will you making PR?

**Comment by RR-08** [comment]
By Saturday.

**Comment by RR-08** [comment]
@GovindSingh9447 Sir, have a look if it's good to go [https://www.figma.com/file/gfJXd5orZ5BJKIRsIg1Mgv/ChatAppUI?node-id=0%3A1](ChatAppUi)

**Comment by RR-08** [comment]
@GovindSingh9447 Sir have a look if it's good to go. [Chat App UI](https://www.figma.com/file/gfJXd5orZ5BJKIRsIg1Mgv/ChatAppUI?node-id=0%3A1)

**Comment by GovindSingh9447** [comment]
> @GovindSingh9447 Sir have a look if it's good to go. [Chat App UI](https://www.figma.com/file/gfJXd5orZ5BJKIRsIg1Mgv/ChatAppUI?node-id=0%3A1)

@RR-08  It's look  good. What about other screens

**Comment by RR-08** [comment]
> @RR-08 It's look good. What about other screens.

@GovindSingh9447 Sir if I'm not mistaken the feature of adding post is missing rest all the screens/features mentioned are there. The home page has the message list. 
What else do I need to add or change?

**Comment by GovindSingh9447** [comment]
> > @RR-08 It's look good. What about other screens.
> 
> @GovindSingh9447 Sir if I'm not mistaken the feature of adding post is missing rest all the screens/features mentioned are there. The home page has the message list. What else do I need to add or change?

Okay. 
There is no need of any changes. 
Make a PR

**Comment by GovindSingh9447** [comment]
@RR-08  we want to post your design on Our Dezenix Insta Page.
So can you make a Insta post ??

**Comment by RR-08** [comment]
> @RR-08  we want to post your design on Our Dezenix Insta Page.
> So can you make a Insta post ??
Yes Sure.

**Comment by GovindSingh9447** [comment]
> > @RR-08  we want to post your design on Our Dezenix Insta Page.
> > So can you make a Insta post ??
> 
> Yes Sure.

Do it by today.

**Comment by RR-08** [comment]
> Do it by today.
@GovindSingh9447 sir here are the images.
[Chatting App UI](https://photos.app.goo.gl/8i4rsA8mExCuQSjo8)

**Comment by GovindSingh9447** [comment]
> > Do it by today.
> 
> @GovindSingh9447 sir here are the images. [Chatting App UI](https://photos.app.goo.gl/8i4rsA8mExCuQSjo8)

Well done, 
You have really done a great work @RR-08 .
Now you can choose & work on any other issues.
